# Generated by Django 4.2.17 on 2025-01-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230901_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Search',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='term',
            name='mapping',
            field=models.ManyToManyField(blank=True, to='core.term'),
        ),
    ]
