# Generated by Django 4.2.18 on 2025-01-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_compositeledger_filtermetadata_filterrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCVDownstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcv_api_endpoint', models.CharField(help_text='Enter the LCV Instance API endpoint', max_length=200)),
                ('lcv_api_endpoint_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=200)),
                ('lcv_api_key', models.CharField(help_text='Enter the LCV API Key', max_length=128)),
                ('source_name', models.CharField(help_text='Enter the name to send data as', max_length=200)),
                ('composite_experiences', models.ManyToManyField(blank=True, related_name='lcv_destination', to='core.compositeledger')),
                ('filter_metadata', models.ManyToManyField(blank=True, related_name='lcv_downstream', to='core.filtermetadata')),
                ('filter_records', models.ManyToManyField(blank=True, related_name='lcv_downstream', to='core.filterrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='CCVDownstream',
        ),
    ]
