# Generated by Django 3.2.9 on 2022-03-07 10:00
import logging

from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations

GROUPS = ['System Operator', 'Experience Owner', 'Experience Manager',
          'Experience Facilitator', 'Experience Participant']
OLD_MODELS = ['catalogs', 'list experiences', 'experiences']
NEW_MODELS = ['xis available catalogs', 'xis catalog', 'xis experience']
PERMISSIONS = ['view', 'add', 'change', 'delete']

# function
def forwards_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Perm = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for custom in OLD_MODELS:
        ct = ContentType.objects.filter(
            model=custom.replace(" ", "")
        )
        if ct.exists():
            ct.delete()

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_contenttypes(app_config, verbosity=0)
        app_config.models_module = None

    for custom in NEW_MODELS:
        ContentType.objects.get_or_create(
            app_label='api',
            model=custom.replace(" ", "")
        )

    for group in GROUPS:
        new_group, created = Group.objects.get_or_create(name=group)

        for model in NEW_MODELS:
            for permission in PERMISSIONS:
                name = 'Can {} {}'.format(permission, model)
                print("Creating {}".format(name))

                model_comb = model
                value = model_comb.replace(" ", "")
                codename = '{}_{}'.format(permission, value)

                try:
                    content_type = \
                        ContentType.objects.get(model=value)
                    model_add_perm, created = \
                        Perm.objects.get_or_create(codename=codename,
                                                   name=name,
                                                   content_type=
                                                   content_type)
                except Perm.DoesNotExist:
#                    logging.warning("Permission not found with name '{}'.".
#                                    format(name))
                    logging.warning("Permission not found with name %s", name)
                    continue

                new_group.permissions.add(model_add_perm)

    print("Updated permission names.")

# function
def reverse_func(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for custom in NEW_MODELS:
        ct = ContentType.objects.filter(
            model=custom.replace(" ", "")
        )
        if ct.exists():
            ct.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_move_permissions'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
