pid /tmp/nginx.pid;

include /etc/nginx/modules-enabled/*.conf;

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include           mime.types;
    default_type      application/octet-stream;
    sendfile          on;
    keepalive_timeout 65;

    proxy_buffer_size         128k;
    proxy_buffers             4 256k;
    proxy_busy_buffers_size   256k;

    client_body_in_file_only  clean;
    client_body_buffer_size   32k;
    client_max_body_size      300M;

    # drop requests with no valid Host:
    server {
        listen       80;
        server_name  _;
        return       444;
    }

    # allow ACME HTTP-01
    server {
        listen      80;
        server_name $SERVER_NAME;
        location ~ ^/\.well-known/acme-challenge/ {
            root    /usr/share/nginx/html;
            allow   all;
        }
        # redirect everything else to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen       443 ssl http2;
        server_name  $SERVER_NAME;

        ssl_certificate      /usr/share/keys/live/$SERVER_NAME/fullchain.pem;
        ssl_certificate_key  /usr/share/keys/live/$SERVER_NAME/privkey.pem;
        ssl_protocols        TLSv1.2 TLSv1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;

        send_timeout           600;
        proxy_connect_timeout  600;
        proxy_send_timeout     600;
        proxy_read_timeout     600;

        include /etc/nginx/proxy_headers.conf;


        location / {
            add_header Content-Security-Policy "default-src 'self'; form-action 'self';" always;

            proxy_pass http://app:8020;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Bolt protocol over HTTP-upgrade
        location /bolt/ {
            rewrite ^/bolt/(.*)$ /$1 break;

            proxy_http_version 1.1;
            proxy_set_header   Upgrade     $http_upgrade;
            proxy_set_header   Connection  "Upgrade";
            proxy_set_header   Host         $host;
            proxy_set_header   X-Real-IP    $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_pass         http://neo4j:7687/;
        }

        # Neo4j Browser UI

        location /browser {
            return 301 /browser/;
        }
        location /browser/ {
            proxy_set_header Accept-Encoding "";
            sub_filter           'return new WebSocket(e)' 'return new WebSocket(e+"/bolt/")';
            sub_filter_once      off;
            sub_filter_types     "*";

            proxy_pass           http://neo4j:7474/browser/;
            proxy_set_header     Host              $host;
            proxy_set_header     X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header     X-Forwarded-Proto $scheme;
        }

        # (optional) static and media, if still needed
        location /static/ {
            alias    /tmp/app/openlxp-xss/static/;
            try_files $uri $uri/ =404;
            expires  30d;
            add_header Cache-Control "public, no-transform";
        }
        location /media/ {
            alias    /tmp/app/openlxp-xss/media/;
            try_files $uri $uri/ =404;
            expires  30d;
            add_header Cache-Control "public, no-transform";
        }
    }
}
