"""
Django settings for openlxp_xss_project project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import mimetypes
import os
import sys
from pathlib import Path
from .neo4j_config import configure_neo4j

import logging

logger = logging.getLogger('dict_config_logger')
NEO4J_HOST = os.environ.get('NEO4J_HOST', 'neo4j')
NEO4J_PORT = os.environ.get('NEO4J_PORT', 7687)
NEO4J_USER = os.environ.get('NEO4J_USER', 'neo4j')
NEO4J_PASSWORD = os.environ.get('NEO4J_PASSWORD', 'password')
NEO4J_DATABASE = os.environ.get('NEO4J_DATABASE', 'neo4j')

try:
    configure_neo4j(neo4j_host=NEO4J_HOST, neo4j_port=NEO4J_PORT, neo4j_user=NEO4J_USER, neo4j_password=NEO4J_PASSWORD, neo4j_database=NEO4J_DATABASE)
except Exception as e:
    logger.error(f"Failed to connect to Neo4j: {e}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CCV = os.environ.get('CCV', False)

HF_HOME = os.environ.get('HF_HOME', '/temp/app/huggingface')
SEMANTIC_MODEL_PATH = os.path.join(HF_HOME, 'bi-encoder-similarity')
CROSS_ENCODER_PATH = os.path.join(HF_HOME, 'fine-tuned-cross-encoder')
NLTK_DATA = os.environ.get('NLTK_DATA', '/temp/app/nltk_data')

INSTANCE_ID = os.environ.get('INSTANCE_ID')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY_VAL')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'false').lower() in ('1', 'true', 'yes')

mimetypes.add_type("text/css", ".css", True)

ALLOWED_HOSTS = os.environ.get('HOSTS').split(';')

# Content Security Policy (CSP)
SELF = "'self'"
IMG_DATA = "data:"

style_hash = os.environ.get("STYLE_SHA")
image_hash = os.environ.get("IMAGE_SHA")

CSP_DEFAULT_SRC = (SELF,)
CSP_FORM_ACTION = (SELF,)

CSP_SCRIPT_SRC = (
    SELF,
)

CSP_IMG_SRC = (
    SELF,
    IMG_DATA,
)

CSP_FORM_ACTION = (
    SELF,
)

_style_src = [SELF,]
if style_hash:
    _style_src.append(f"'{style_hash}'")
if image_hash:
    _style_src.append(f"'{image_hash}'")
    
CSP_STYLE_SRC = tuple(_style_src)
CSP_FRAME_SRC = (SELF,)
CSP_FONT_SRC = (SELF,)

# Application definition

INSTALLED_APPS = [
    'django_neomodel',
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'core.apps.CoreConfig',
    'api',
    'users',
    'uid',
    # 'social_django',
    'common',
    'deconfliction_service',
    'p1_auth',
]

SECURE_BROWSER_XSS_FILTER = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_SECONDS = 365 * 24 * 60 * 60
SECURE_HSTS_PRELOAD = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'p1_auth.middleware.AuthenticateSessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

SESSION_COOKIE_SECURE = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

ROOT_URLCONF = 'openlxp_xss_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openlxp_xss_project.wsgi.application'

## Encryption key for django-encrypted-model-fields

FIELD_ENCRYPTION_KEY = 'NzVkgiLCyzOePBWCKvUTc38M4YWiQjsD0zc9m7x_iLo='

CORS_ALLOWED_ORIGIN_REGEXES = [
    os.environ.get("CORS_ALLOWED_ORIGIN_REGEXES", r"^https://.*\.ldss\.tla\.adlnet\.gov$")
]

CORS_ALLOW_CREDENTIALS = True

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_DOMAIN = os.environ.get('CSRF_COOKIE_DOMAIN')
SERVER_NAME = os.environ.get('SERVER_NAME')
BASE_URL = os.environ.get('BASE_URL')
CSRF_TRUSTED_ORIGINS = []
if BASE_URL:
    CSRF_TRUSTED_ORIGINS.append(BASE_URL)
elif SERVER_NAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{SERVER_NAME}")

CCV= os.environ.get('CCV', False)

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': 3306,
        'OPTIONS': {
            'ssl_disabled': True,
            'sql_mode': 'STRICT_TRANS_TABLES',
            },
        'TEST': {
            'NAME': f"test_{os.environ.get('DB_NAME')}",
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'openlxp_xss_project.validators.MaximumLengthValidator',
        'OPTIONS': {
            'max_length': 20
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USES_SSL_PROXY = os.environ.get("USES_SSL_PROXY") == "true"
FORCE_HTTP = os.environ.get("FORCE_HTTP") == "true"

if USES_SSL_PROXY or FORCE_HTTP:
    SECURE_SSL_REDIRECT = False
else:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
LOG_PATH = os.environ.get('LOG_PATH')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if os.environ.get('FORCE_SCRIPT_NAME') is not None:
    FORCE_SCRIPT_NAME = os.environ.get('FORCE_SCRIPT_NAME')
    # print("FORCE_SCRIPT_NAME:", FORCE_SCRIPT_NAME)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SHOW_VERBOSE_LOGS = os.getenv('SHOW_VERBOSE_LOGS', 'false').lower() in ('1', 'true', 'yes')
LOG_LEVEL = 'INFO' if SHOW_VERBOSE_LOGS else 'WARNING'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'loggers': {
        'dict_config_logger': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'simpleRe',
            'level': LOG_LEVEL,
        },
    },

    'formatters': {
        'simpleRe': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        }
    }
}

AUTH_USER_MODEL = 'users.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'p1_auth.backends.PlatformOneRestAuthentication',
    ],
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'p1_auth.backends.PlatformOneAuthentication',

)

# openlxp_authentication settings openlxp_authentication documentation:
# https://github.com/OpenLXP/openlxp-authentication#readme
# social_django documentation:
# https://python-social-auth.readthedocs.io/en/latest/index.html
# SOCIAL_AUTH_STRATEGY = 'openlxp_authentication.models.SAMLDBStrategy'
JSONFIELD_ENABLED = True
USER_MODEL = 'users.CustomUser'
SESSION_EXPIRATION = True

if os.environ.get('LOGIN_REDIRECT_URL') is not None:
    LOGIN_REDIRECT_URL = os.environ.get('LOGIN_REDIRECT_URL')

if os.environ.get('OVERIDE_HOST') is not None:
    OVERIDE_HOST = os.environ.get('OVERIDE_HOST')
    BAD_HOST = os.environ.get('BAD_HOST')

if os.environ.get('STRATEGY') is not None:
    SOCIAL_AUTH_STRATEGY = os.environ.get('STRATEGY')

SP_ENTITY_ID = os.environ.get('ENTITY_ID')

SP_PUBLIC_CERT = os.environ.get('SP_PUBLIC_CERT')
SP_PRIVATE_KEY = os.environ.get('SP_PRIVATE_KEY')
ORG_INFO = {
    "en-US": {
        "name": "example",
        "displayname": "Example Inc.",
        "url": "http://localhost",
    }
}
TECHNICAL_CONTACT = {
    "givenName": "Tech Person",
    "emailAddress": "technical@localhost.com"
}
SUPPORT_CONTACT = {
    "givenName": "Support Person",
    "emailAddress": "support@localhost.com",
}
USER_ATTRIBUTES = [
    "user_permanent_id",
    "first_name",
    "last_name",
    "email"
]

# directory to store files during upload scanning
if os.environ.get('TMP_SCHEMA_DIR') is not None and\
        len(os.environ.get('TMP_SCHEMA_DIR')) > 0:
    TMP_SCHEMA_DIR = os.environ.get('TMP_SCHEMA_DIR')
else:
    TMP_SCHEMA_DIR = os.path.join(BASE_DIR, 'tmp', 'schemas')

TMP_SCHEMA_DIR = os.path.join(TMP_SCHEMA_DIR, '')

# P1-AUTH SETTINGS

USER_ATTRIBUTES_MAP = {
    'last_name': 'family_name',
    'first_name': 'given_name',
    'email': 'email'
}

USER_MEMBERSHIPS = {
    'groups': {
        'name': 'group-simple'
    },
}

JWT_PREFERRED_USERNAME_FIELD = "email"

if os.environ.get('STAFF_FLAG') is not None:
    USER_STAFF_FLAG = os.environ.get('STAFF_FLAG')

if os.environ.get('STAFF_VALUE') is not None:
    USER_STAFF_VALUE = os.environ.get('STAFF_VALUE')

if os.environ.get('SU_FLAG') is not None:
    USER_SUPERUSER_FLAG = os.environ.get('SU_FLAG')

if os.environ.get('SU_VALUE') is not None:
    USER_SUPERUSER_VALUE = os.environ.get('SU_VALUE')

if os.environ.get('REQUIRE_JWT') is not None:
    REQUIRE_JWT = True
