# nginx.default


include /etc/nginx/mime.types;

server {
    listen 8080;
    server_name ldss.staging.dso.mil;

    location /static {
        disable_symlinks on;
        root /usr/share/nginx/html;
    }

    location /media {
        disable_symlinks on;
        root /usr/share/nginx/html;
    }

    location / {
        proxy_pass http://localhost:8020;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
