apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldss-xia-dau
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    spec:
      serviceAccountName: s3-role
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
        - name: code-il2-pull-creds
      containers:
        - name: ldss-xia-dau
          image: ldss/ldss-xia-dau
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - mountPath: "/var/shared/"
              name: xia-dau-storage-mount
          command:
            - "/bin/sh"
            - "-exc"
            - |
              echo "Checking PATH..."
              echo $PATH
              echo "Checking Python version..."
              if command -v python3 &> /dev/null
              then
                  python3 --version
                  echo "Python3 path: $(which python3)"
              else
                  echo "Python3 is not installed"
              fi

              echo "Searching for Gunicorn..."
              GUNICORN_PATH=$(find / -name gunicorn -type f 2>/dev/null | head -n 1)
              if [ -n "$GUNICORN_PATH" ]; then
                  echo "Gunicorn found at: $GUNICORN_PATH"
                  GUNICORN_DIR=$(dirname "$GUNICORN_PATH")
                  export PATH="$GUNICORN_DIR:$PATH"
                  echo "Updated PATH: $PATH"
              else
                  echo "Gunicorn is not installed. Installing it now..."
                  python3 -m pip install --user gunicorn
                  GUNICORN_PATH=$(find / -name gunicorn -type f 2>/dev/null | head -n 1)
                  if [ -n "$GUNICORN_PATH" ]; then
                      echo "Gunicorn installed at: $GUNICORN_PATH"
                      GUNICORN_DIR=$(dirname "$GUNICORN_PATH")
                      export PATH="$GUNICORN_DIR:$PATH"
                      echo "Updated PATH: $PATH"
                  else
                      echo "Failed to install Gunicorn."
                      exit 1
                  fi
              fi

              echo "Checking Gunicorn installation..."
              if command -v gunicorn &> /dev/null
              then
                  echo "Gunicorn is installed and accessible."
                  echo "Gunicorn path: $(which gunicorn)"
              else
                  echo "Gunicorn is still not accessible. Exiting."
                  exit 1
              fi

              sed -i '1s|^.*$|#!/usr/bin/python3|' /var/app/.cache/python-packages/bin/gunicorn
              sed -i 's/hashlib.md5()/hashlib.md5(usedforsecurity=False)/g' /var/app/.cache/python-packages/django/db/backends/utils.py
              ../start-app.sh
          envFrom:
            - configMapRef:
                name: app-name
            - configMapRef:
                name: app-vars
            - secretRef:
                name: app-db-credentials
            - secretRef:
                name: mysql-connect-info
            - secretRef:
                name: xia-dau-secrets
            - configMapRef:
                name: cluster-prefix
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: S3_BUCKET_NAME
              value: pb-mdo-$(NAMESPACE)-$(CLUSTER_PREFIX)
            - name: S3_REGION
              value: us-gov-west-1
            - name: S3_ENDPOINT_URL
              value: https://s3.us-gov-west-1.amazonaws.com
            - name: LOG_PATH
              value: "/var/debug.log"
            - name: STAFF_FLAG
              value: group-full
            - name: SU_FLAG
              value: group-full
            - name: STAFF_VALUE
              value: /Platform One/Products/adl-ousd/LDSS/IL2/roles/USER_STAFF
            - name: SU_VALUE
              value: /Platform One/Products/adl-ousd/LDSS/IL2/roles/USER_SUPERUSER
            - name: FORCE_SCRIPT_NAME
              value: "/ldss-xia-dau"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-connect-info
                  key: MYSQL_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_NAME_5
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_ADMIN_USER_5
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_ADMIN_PASSWORD_5
            - name: MYSQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_NAME_5
            - name: MYSQL_DB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_ADMIN_USER_5
            - name: MYSQL_DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_ADMIN_PASSWORD_5
            - name: MYSQL_DB_RW_USER
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_RW_USER_5
            - name: MYSQL_DB_RW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_RW_PASSWORD_5
            - name: MYSQL_DB_RO_USER
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_RO_USER_5
            - name: MYSQL_DB_RO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: MYSQL_DB_RO_PASSWORD_5
        - name: xia-dau-nginx
          image: registry1.dso.mil/ironbank/opensource/nginx/nginx:1.27.3
          ports: 
            - containerPort: 8080
              name: dau-nginx-port
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: xia-dau-storage-mount
            - mountPath: /etc/nginx/conf.d/
              name: nginx-default
      volumes:
        - name: xia-dau-storage-mount
          persistentVolumeClaim:
            claimName: xia-dau-storage-claim
        - name: nginx-default
          configMap:
            name: xia-dau-nginx-default-config
