apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: ldss-xia-dau
  authentication: istio-auth

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
- name: xia-dau-nginx-default-config
  files:
  - nginx.conf