FROM registry1.dso.mil/ironbank/opensource/nodejs/nodejs18:18.20 AS builder
USER root
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ENV CI=1
RUN NODE_OPTIONS="--openssl-legacy-provider --max_old_space_size=3072" yarn build
USER node

FROM registry1.dso.mil/ironbank/opensource/nodejs/nodejs18:18.20 AS runner
USER node
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/.next/static/media /ecc-openlxp-xds-ui/.next/static/media/
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
USER root
RUN mkdir /app/.next/cache/images
RUN chmod 777 /app/.next/cache/images
RUN chown -R node:node /app/.next/cache/images
#USER nextjs
USER node
EXPOSE 3000
ENV NEXT_TELEMETRY_DISABLED 1
CMD ["yarn", "start"]