# Generated by Django 3.1.14 on 2022-03-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMSConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_xis_host', models.CharField(default='http://openlxp-xis:8020/api/catalogs', help_text='Enter the XIS host to query data', max_length=200)),
            ],
            options={
                'verbose_name': 'XMS Connection',
            },
        ),
    ]
