# Generated by Django 3.1.14 on 2022-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_auto_20220607_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmsconfigurations',
            name='target_xis_host',
            field=models.CharField(help_text='Enter the XIS host to query data', max_length=200),
        ),
    ]
