# Generated by Django 3.1.14 on 2022-08-18 15:39

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configurations', '0004_auto_20220609_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInformationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_title', models.CharField(default='metadata.Course.CourseTitle', help_text='Enter the mapping for the title of the course found in XIS', max_length=200)),
                ('course_short_description', models.CharField(default='metadata.Course.CourseShortDescription', help_text='Enter the mapping for the short description of the course found in XIS', max_length=200)),
                ('course_full_description', models.CharField(default='metadata.Course.CourseFullDescription', help_text='Enter the mapping for the full description of the course found in XIS', max_length=200)),
                ('course_code', models.CharField(default='metadata.Course.CourseCode', help_text='Enter the mapping for the code of the course found in XIS', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='xmsconfigurations',
            name='default_user_group',
            field=models.ForeignKey(blank=True, help_text='Select the group to assign new users to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
