# Generated by Django 3.1.14 on 2023-05-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmsconfigurations',
            name='xis_api_key',
            field=models.CharField(default='INVALID KEY', help_text='Enter the XIS API Key', max_length=40),
            preserve_default=False,
        ),
    ]
